### ISSUE TITLE
Questions from Roman

### ISSUE THREAD

**Issue by 5HT** [groupoid/infinity#9]
**Роман:**
Здравствуйте. Я заинтересовался вашим проектом, но нигде не могу найти
документации. Есть немного в
https://github.com/groupoid/om/tree/master/doc , но там нет самого
интересного — того, как вы получаете элиминаторы из рекурсоров. Есть
ли где-нибудь описание этого процесса? Связан ли ваш метод с Self
Types за авторством Peng Fu?

**Comment by 5HT** [comment]
Спасибо за ответ. К сожалению, я не разбираюсь в теории категорий, так
что мало что понял. Вы случайно не планируете когда-нибудь изложить
также операционную семантику, meaning explanations или что-нибудь
подобное в computational духе?

Одна вещь, которая меня смущает: возможность взять и определить тип
свободных монад, который не является строго позитивным, что ведет к
парадоксам: http://lpaste.net/173573
В вашей системе это работает как-то по-другому?

**Comment by 5HT** [comment]
Операционная сематика будет! Если хочешь можешь подключаться к проекты, будешь ее выписывать :-)

**Comment by 5HT** [comment]
Приходи сюда: https://gitter.im/groupoid/exe

**Comment by zraffer** [comment]
Я тут по-корректнее отвечу :)

Такого, как написано в приведенном фрагменте кода у нас сделать нельзя, поскольку свободная монада строится, по определению, на функторе, а там был приведен не функтор.

Тем не менее парадоксы с функторами пожно привести, это все из-за непредикативности универсумов, используемых в нижнем уровне ОМ.

Выходов из этой ситуации целых три:

- описать кодировку для ограниченного фрагмената CIC, которая будет помещаться в CoC 
- описать кодировку для предикативной иерархии
- использовать предикативную иерархию в EXE и непредикативную в OM

последний вариант немного хакерский, но похоже самый простой и эффективный
